application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /style
  static_dir: style

- url: /img
  static_dir: img

- url: /script
  static_dir: script

- url: /.*
  script: scrumsize.application